openapi: 3.0.0
info:
  title: gameSagaAPI
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/game-saga/{sagaId}/related-sagas':
    parameters:
      - schema:
          type: string
        name: sagaId
        in: path
        required: true
    get:
      operationId: get-game-saga-related-sagas
      summary: Gets the related game sagas
      description: Returns the related game sagas to a given one ordered by relevance
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelatedGameSagas'
        '404':
          description: No saga found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        '500':
          description: An error occurred while trying to retrieve the ids of sagas related with the id 2000
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
components:
  schemas:
    RelatedGameSagas:
      type: array
      description: 'List of related game saga IDs to a given one ordered by relevance'
      minItems: 0
      uniqueItems: true
      items:
        type: string
    Error404:
      type: object
      properties:
        errorCode:
          type: integer
          example: 404
        errorText:
          type: string
          example: No saga found
    Error500:
      type: object
      properties:
        errorCode:
          type: integer
          example: 500
        errorText:
          type: string
          example: An error occurred while trying to retrieve the ids of sagas related with the id 2000