openapi: 3.0.0
info:
  title: VideoGamesAPI
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  '/game/{gameId}/saga':
    get:
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sagas'
        '404':
          description: No saga found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        '500':
          description: An error occurred while trying to retrieve the sagas from the game ID 2000
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
components:
  schemas:
    Sagas:
      type: array
      description: 'List of game sagas related to a given game ordered by relevance'
      minItems: 0
      uniqueItems: true
      items:
        $ref: '#/components/schemas/Game'
    Game:
      description: 'Game detail'
      type: object
      properties:
        id:
          type: string
          minLength: 1
        title:
          type: string
          minLength: 1
        genre:
          type: string
        releaseDate:
          type: string
          format: date
      required:
        - id
        - title
        - genre
        - releaseDate
    Error404:
      type: object
      properties:
        errorCode:
          type: integer
          example: 404
        errorText:
          type: string
          example: No saga found
    Error500:
      type: object
      properties:
        errorCode:
          type: integer
          example: 500
        errorText:
          type: string
          example: An error occurred while trying to retrieve the sagas from the game ID 2000